# ===================================
# Experiment Configuration
# ===================================

[graphing]
oct_type = "monochromatic"          # options: "monochromatic", "nonmonochromatic", "quantum"
grover = true              # uses the beam splitter (standard) or the Grover coin
time_limit = 2                # seconds
y_limit = 1.5                   # unitless (?)
display_interferogram = true
display_scaled_interferogram = true
scale_max = false
display_sample = true

[sample]
length = 90e-6         # meters
refractive_index = 1.5        # unitless
initial_depth = 180.0          # micrometers (?)
entering_reflectance = 0.2    # percent of light
entering_reflectance_narrowness = 10
exiting_reflectance = 0.2     # percent of light
exiting_reflectance_narrowness = 10
shape = "square" # options: "gaussian", "cornered", "square"

[laser]
central_wavelength = 0.800    # micrometers
spectral_width = 3.8e13       # radians / second
